# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-01 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='media/articles/default.png', upload_to='articles/'),
        ),
    ]
