# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20191001_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecepients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
