# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsletterrecepients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecepients',
            new_name='NewsLetterRecipients',
        ),
    ]
